import { Mastra } from '@mastra/core';
import { Workflow, createStep } from '@mastra/core/workflows';
import { execSync } from 'child_process';
import { z } from 'zod';
import * as fs from 'fs';
import * as path from 'path';

// Define the Step for generating the schema
const generateSchemaStep = createStep({
  id: 'generateSchema',
  inputSchema: z.object({
    tags: z.array(z.object({
      tag: z.string(),
      namespace: z.string(),
      domain: z.string()
    }))
  }),
  outputSchema: z.object({
    results: z.array(z.object({
      tag: z.string(),
      namespace: z.string(),
      domain: z.string(),
      definition: z.string(),
      attributes: z.array(z.string()),
      parents: z.array(z.string()),
      citation: z.string(),
      sdkClass: z.string()
    }))
  }),
  execute: async ({ inputData }) => {
    const { tags } = inputData;
    const results = [];

    for (const item of tags) {
      const { tag, namespace, domain } = item;
      console.log(`[Workflow] Processing <${namespace}:${tag}>...`);
      
      const prompt = `
You are an expert in the ECMA-376 Office Open XML (OOXML) specification.
Generate a structured RAG reference document for the following XML tag:
- Tag Name: "${tag}"
- Namespace Prefix: "${namespace}"
- Domain: "${domain}"

You must return a JSON object conforming exactly to this JSON schema:
{
  "type": "object",
  "properties": {
    "tag": { "type": "string" },
    "namespace": { "type": "string" },
    "domain": { "type": "string" },
    "definition": { "type": "string" },
    "attributes": { "type": "array", "items": { "type": "string" } },
    "parents": { "type": "array", "items": { "type": "string" } },
    "citation": { "type": "string" },
    "sdkClass": { "type": "string" }
  },
  "required": ["tag", "namespace", "domain", "definition", "attributes", "parents", "citation", "sdkClass"]
}

Guidelines:
1. "namespace": You MUST return the short prefix (e.g., "w" for WordprocessingML, "r" for SpreadsheetML/Relationships, "p" for PresentationML) instead of the full XML namespace URI.
2. "definition": Provide a clear, precise explanation of what this element configures and its role. Keep it descriptive but concise (2-3 sentences).
3. "citation": You MUST reference the most specific section number in the ECMA-376 specification that defines this specific element. Do NOT use high-level parent section numbers. For example, the element `document` is defined in `ECMA-376 Part 1, Section 17.2.3`, not the general `Section 17.2` or the incorrect `Section 17.3.1.10`. In case of multiple citations, pick the one that is the section heading and talks about that particular element only. Must match the format: "ECMA-376 Part X, Section Y.Z" (e.g. "ECMA-376 Part 1, Section 17.3.1.22"). Verify the exact section number.
4. "sdkClass": Provide the corresponding Microsoft Open XML SDK class name (e.g. "Paragraph" or "TableCell").

Return ONLY the raw JSON block. No markdown wrapper, no explanations.
`;

      // Escape prompt for CLI execution
      const escapedPrompt = prompt.replace(/"/g, '\\"').replace(/`/g, '\\`');
      const command = `jetski --print "${escapedPrompt}"`;
      
      try {
        const stdout = execSync(command, { encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] });
        
        // Extract JSON block from output
        const jsonMatch = stdout.match(/\{[\s\S]*\}/);
        if (!jsonMatch) {
          throw new Error(`Could not find JSON in jetski output: ${stdout}`);
        }
        
        const doc = JSON.parse(jsonMatch[0].trim());
        results.push(doc);
        console.log(`[Workflow] Successfully processed <${namespace}:${tag}>`);
      } catch (error) {
        console.error(`[Workflow] Failed to process <${namespace}:${tag}>:`, error);
      }

      // Avoid rate limits
      await new Promise(resolve => setTimeout(resolve, 2000));
    }

    return { results };
  }
});

// Define the Step for compiling the knowledge base
const compileKBStep = createStep({
  id: 'compileKB',
  inputSchema: z.object({
    results: z.array(z.object({
      tag: z.string(),
      namespace: z.string(),
      domain: z.string(),
      definition: z.string(),
      attributes: z.array(z.string()),
      parents: z.array(z.string()),
      citation: z.string(),
      sdkClass: z.string()
    }))
  }),
  outputSchema: z.object({
    success: z.boolean(),
    count: z.number()
  }),
  execute: async ({ inputData }) => {
    const { results } = inputData;
    
    // 1. Write to public/generated-rag.json
    const outputPath = path.join(process.cwd(), 'public/generated-rag.json');
    fs.writeFileSync(outputPath, JSON.stringify(results, null, 2), 'utf8');
    console.log(`[Workflow] Wrote generated RAG database to: ${outputPath}`);

    // 2. Write to services/staticKnowledgeBase.ts
    const kbPath = path.join(process.cwd(), 'services/staticKnowledgeBase.ts');
    const codeContent = `// This file is auto-generated by compileKB step in ooxml-rag-ingestion workflow.
// Do not edit this file manually.

export interface ReferenceDoc {
  tag: string;
  namespace: string;
  domain: 'docx' | 'xlsx' | 'pptx' | 'shared';
  definition: string;
  attributes: string[];
  parents: string[];
  citation?: string;
  sdkClass?: string;
}

export const KNOWLEDGE_BASE: ReferenceDoc[] = ${JSON.stringify(results, null, 2)};
`;
    fs.writeFileSync(kbPath, codeContent, 'utf8');
    console.log(`[Workflow] Compiled static knowledge base to: ${kbPath}`);

    return { success: true, count: results.length };
  }
});

// Define the Mastra Workflow for RAG Ingestion
export const ingestionWorkflow = new Workflow({
  id: 'ooxml-rag-ingestion',
  inputSchema: z.object({
    tags: z.array(z.object({
      tag: z.string(),
      namespace: z.string(),
      domain: z.string()
    }))
  }),
  outputSchema: z.object({
    success: z.boolean(),
    count: z.number()
  })
});

// Chain the steps and commit the workflow
ingestionWorkflow
  .then(generateSchemaStep)
  .then(compileKBStep)
  .commit();

// Initialize Mastra and export it
export const mastra = new Mastra({
  workflows: {
    'ooxml-rag-ingestion': ingestionWorkflow
  }
});
