/**
 * Semantic diff of two OOXML packages, emitted as **structured records**.
 *
 * The output shape is the point. This is meant to be consumed by another program — an
 * agent reasoning about a codebase, a regression harness — so the payload is typed
 * change records and the prose rendering is derived from them, never the other way
 * round. A well-worded paragraph of explanation is useless to a caller trying to decide
 * which of its own code paths produced a visual delta.
 *
 * Three problems make a naive XML diff worthless here, and each is handled explicitly:
 *
 *   1. **Revision-save noise.** Word stamps `w:rsid*` attributes onto elements to track
 *      editing sessions. They have zero rendering effect, and merely re-saving a file
 *      rewrites enough of them that a textual diff reports the document as heavily
 *      changed. Same for `w:proofErr` (spell-check state) and
 *      `w:lastRenderedPageBreak` (a stale layout cache).
 *
 *   2. **Run splitting.** The same visible sentence can be one `w:r` or twenty, split at
 *      arbitrary points by spell-check state, bookmarks or comment anchors, with
 *      identical formatting on every fragment. A node-level diff calls that a rewritten
 *      paragraph while the rendered text is byte-identical. The fix is to flatten
 *      content to atoms and discard run boundaries entirely.
 *
 *   3. **Formatting expressed differently.** Direct `w:rPr`, a character style, and a
 *      document default can produce identical rendering from completely different
 *      markup. Comparing markup reports a change; comparing *resolved* formatting does
 *      not. This module diffs the resolved values.
 *
 * What is filtered is reported rather than hidden — a consumer needs to know that 47
 * revision ids were discarded, otherwise "no changes" is indistinguishable from
 * "changes I chose not to show you".
 */

import { W_NAMESPACE } from './wordStyleResolver';
import { loadWordContext, analyzeParagraphFormatting } from './wordFormattingAnalysis';
import type { PackageParts } from './packageIntegrity';

/** Attributes that record editing sessions and never affect rendering. */
const RSID_ATTRIBUTES = ['rsid', 'rsidR', 'rsidRPr', 'rsidP', 'rsidTr', 'rsidDel', 'rsidSect', 'rsidRDefault'];

/** Elements that are ephemeral state or a stale cache, regenerated by Word at will. */
const EPHEMERAL_ELEMENTS = ['proofErr', 'lastRenderedPageBreak', 'rsid', 'bookmarkStart', 'bookmarkEnd'];

export interface NormalizationReport {
  rule: string;
  count: number;
}

/**
 * Strips rendering-irrelevant noise from a parsed part, reporting what it removed.
 *
 * Mutates the document. Returns counts so the caller can tell an empty diff from a
 * heavily filtered one.
 */
export const normalizePart = (doc: Document): NormalizationReport[] => {
  const counts = new Map<string, number>();
  const bump = (rule: string) => counts.set(rule, (counts.get(rule) ?? 0) + 1);

  const walk = (element: Element) => {
    for (const attr of Array.from(element.attributes)) {
      if (attr.namespaceURI === W_NAMESPACE && RSID_ATTRIBUTES.includes(attr.localName)) {
        element.removeAttributeNS(W_NAMESPACE, attr.localName);
        bump('revision-save id removed');
      }
    }
    for (const child of Array.from(element.children)) {
      if (child.namespaceURI === W_NAMESPACE && EPHEMERAL_ELEMENTS.includes(child.localName)) {
        bump(`${child.localName} removed`);
        child.remove();
        continue;
      }
      walk(child);
    }
  };

  if (doc.documentElement) walk(doc.documentElement);
  return [...counts.entries()].map(([rule, count]) => ({ rule, count }));
};

/**
 * One atomic piece of content: a character, a paragraph mark, or an embedded object.
 *
 * Atomizing is what makes run boundaries stop mattering. The same text split across one
 * run or twenty produces an identical atom sequence, so the diff sees no change where
 * there is none.
 */
export interface ContentAtom {
  /** `char` for text, `para` for a paragraph mark, `object` for a drawing or field. */
  kind: 'char' | 'para' | 'object';
  value: string;
  /** Index of the paragraph this atom belongs to, for locating a change. */
  paragraph: number;
}

/** Flattens a body part into an atom stream. */
export const atomize = (doc: Document): ContentAtom[] => {
  const atoms: ContentAtom[] = [];
  const paragraphs = Array.from(doc.getElementsByTagNameNS(W_NAMESPACE, 'p'));

  paragraphs.forEach((paragraph, index) => {
    for (const run of Array.from(paragraph.getElementsByTagNameNS(W_NAMESPACE, 'r'))) {
      for (const child of Array.from(run.children)) {
        if (child.namespaceURI !== W_NAMESPACE) continue;
        if (child.localName === 't') {
          for (const ch of child.textContent ?? '') {
            atoms.push({ kind: 'char', value: ch, paragraph: index });
          }
        } else if (['drawing', 'pict', 'object', 'fldChar'].includes(child.localName)) {
          atoms.push({ kind: 'object', value: child.localName, paragraph: index });
        }
      }
    }
    // The paragraph mark is content: splitting or merging paragraphs is a real change.
    atoms.push({ kind: 'para', value: '¶', paragraph: index });
  });

  return atoms;
};

export type ChangeKind =
  | 'content-inserted'
  | 'content-deleted'
  | 'formatting-changed'
  | 'part-added'
  | 'part-removed';

/**
 * One difference, in a form another program can act on.
 *
 * Deliberately flat and typed. A consumer deciding which of its code paths produced a
 * delta needs `property`, `before` and `after` as fields, not sentences to parse.
 */
export interface ChangeRecord {
  kind: ChangeKind;
  /** Package part path, e.g. `word/document.xml`. */
  part: string;
  /** Where in the part: a paragraph index, or the part itself. */
  location: string;
  /** For formatting changes, the property name, e.g. `b`, `sz`, `ind`. */
  property?: string;
  before: string | null;
  after: string | null;
  /**
   * Whether a reader would see this.
   *
   * Noise is filtered out by normalization, but some surviving changes are still
   * structural rather than visual. A consumer chasing a *visual* regression wants to
   * filter on this rather than re-deriving it.
   */
  visible: boolean;
  /**
   * What to change to make the two sides match, phrased as an instruction.
   *
   * Direction is always "make the second package match the first", so a caller can
   * apply the list without having to work out which way round each item runs.
   */
  remediation: string;
}

export interface DiffResult {
  /**
   * True when the two packages will render identically, whatever a textual diff says.
   *
   * This is the most useful single answer the module produces for a human staring at a
   * raw XML diff full of red. Two files can differ in thousands of bytes - rewritten
   * revision ids, text redistributed across runs, formatting moved between a style and
   * direct properties - and be treated identically by Word. Saying so plainly is worth
   * more than listing what differs textually.
   */
  equivalent: boolean;
  records: ChangeRecord[];
  /** Parts examined, in order. */
  parts: string[];
  /** What normalization discarded, so an empty diff is distinguishable from a filtered one. */
  normalized: NormalizationReport[];
  /** What could not be established. Travels with the result as a contract. */
  unresolved: string[];
}

/** Longest common subsequence over atoms, by kind and value. */
const diffAtoms = (before: ContentAtom[], after: ContentAtom[]): { inserted: ContentAtom[]; deleted: ContentAtom[] } => {
  const key = (a: ContentAtom) => `${a.kind}:${a.value}`;
  const n = before.length;
  const m = after.length;

  // Guard against pathological input rather than allocating an enormous table.
  if (n * m > 4_000_000) {
    return { inserted: after, deleted: before };
  }

  const table: number[][] = Array.from({ length: n + 1 }, () => new Array<number>(m + 1).fill(0));
  for (let i = n - 1; i >= 0; i--) {
    for (let j = m - 1; j >= 0; j--) {
      table[i][j] = key(before[i]) === key(after[j])
        ? table[i + 1][j + 1] + 1
        : Math.max(table[i + 1][j], table[i][j + 1]);
    }
  }

  const inserted: ContentAtom[] = [];
  const deleted: ContentAtom[] = [];
  let i = 0;
  let j = 0;
  while (i < n && j < m) {
    if (key(before[i]) === key(after[j])) { i++; j++; }
    else if (table[i + 1][j] >= table[i][j + 1]) { deleted.push(before[i]); i++; }
    else { inserted.push(after[j]); j++; }
  }
  while (i < n) deleted.push(before[i++]);
  while (j < m) inserted.push(after[j++]);

  return { inserted, deleted };
};

/** Groups consecutive atoms from the same paragraph into one record. */
const groupAtoms = (atoms: ContentAtom[]): { paragraph: number; text: string }[] => {
  const groups: { paragraph: number; text: string }[] = [];
  for (const atom of atoms) {
    const last = groups[groups.length - 1];
    if (last && last.paragraph === atom.paragraph) last.text += atom.value;
    else groups.push({ paragraph: atom.paragraph, text: atom.value });
  }
  return groups;
};

const bodyPartPattern = /^word\/(?:document\d*|header[^/]*|footer[^/]*|footnotes\d*|endnotes\d*|comments\d*)\.xml$/;

/**
 * Renders a resolved property as a comparable string.
 *
 * Comparing `w:val` alone is not enough, and the failure is quiet: `w:ind` carries its
 * meaning in `w:left`/`w:hanging`, `w:spacing` in `w:before`/`w:after`, `w:rFonts` in
 * `w:ascii` and friends. All of them have no `w:val` at all, so a val-only comparison
 * reports every indent change as no change. Attributes are sorted so that markup order
 * cannot masquerade as a difference.
 */
const canonicalise = (property: { element: Element | null } | undefined): string | null => {
  if (!property) return null;
  if (property.element === null) return 'not applied';
  const attributes = Array.from(property.element.attributes);
  if (attributes.length === 0) return 'applied';
  // A property whose whole meaning is `w:val` reads better as the bare value, which is
  // what a consumer would otherwise have to parse back out. Anything richer keeps the
  // attribute form, where the `name=value` shape is unambiguous.
  const only = attributes.length === 1 ? attributes[0] : null;
  if (only && only.localName === 'val') return only.value;
  return attributes.map(attr => `${attr.name}=${attr.value}`).sort().join(' ');
};

/**
 * Compares the resolved formatting of matching paragraphs.
 *
 * Resolved rather than raw: direct properties, a character style and a document default
 * can express the same rendering through entirely different markup, so a markup
 * comparison reports changes a reader would never see — and misses changes where the
 * markup stayed put but an inherited value moved underneath it.
 */
const diffFormatting = (
  beforeParts: PackageParts,
  afterParts: PackageParts,
  part: string,
  unresolved: string[]
): ChangeRecord[] => {
  const records: ChangeRecord[] = [];
  const beforeContext = loadWordContext(beforeParts);
  const afterContext = loadWordContext(afterParts);

  const paragraphsOf = (ctx: ReturnType<typeof loadWordContext>) =>
    ctx.bodyParts.find(bp => bp.path === part)?.document
      ?? (part === 'word/document.xml' ? ctx.document : null);

  const beforeDoc = paragraphsOf(beforeContext);
  const afterDoc = paragraphsOf(afterContext);
  if (!beforeDoc || !afterDoc) return records;

  const beforeParagraphs = Array.from(beforeDoc.getElementsByTagNameNS(W_NAMESPACE, 'p'));
  const afterParagraphs = Array.from(afterDoc.getElementsByTagNameNS(W_NAMESPACE, 'p'));

  // Compare positionally. Content insertions shift indices, so a run of formatting
  // findings after a content change may be spurious - which is why content changes are
  // reported alongside and a consumer should read them together.
  const shared = Math.min(beforeParagraphs.length, afterParagraphs.length);
  for (let index = 0; index < shared; index++) {
    const a = analyzeParagraphFormatting(beforeContext, beforeParagraphs[index]);
    const b = analyzeParagraphFormatting(afterContext, afterParagraphs[index]);
    unresolved.push(...a.unresolved, ...b.unresolved);

    const names = new Set([...a.paragraph.properties.keys(), ...b.paragraph.properties.keys()]);
    for (const name of names) {
      // pStyle and rStyle are the *mechanism* by which formatting arrives, not
      // formatting themselves. Their effect already shows up in the resolved
      // properties, so reporting them too would flag a change whenever markup was
      // reorganised without altering what a reader sees - exactly what this module
      // exists to avoid.
      if (name === 'pStyle' || name === 'rStyle') continue;

      const beforeValue = canonicalise(a.paragraph.properties.get(name));
      const afterValue = canonicalise(b.paragraph.properties.get(name));
      if (beforeValue !== afterValue) {
        records.push({
          kind: 'formatting-changed',
          part,
          location: `paragraph[${index}]`,
          property: name,
          before: beforeValue,
          after: afterValue,
          visible: true,
          // Names the effective value to restore rather than the markup to edit,
          // because the same effective value can be reached several ways - through a
          // style, a document default, or direct properties - and which route to take
          // is the author's call, not this module's.
          remediation: beforeValue === null
            ? `Remove the ${name} formatting from paragraph ${index} of ${part}; it was not set before.`
            : afterValue === null
              ? `Restore ${name} to "${beforeValue}" on paragraph ${index} of ${part}, by whichever route suits - a style, a document default, or direct formatting.`
              : `Change the effective ${name} on paragraph ${index} of ${part} from "${afterValue}" back to "${beforeValue}".`
        });
      }
    }
  }

  return records;
};

/**
 * Diffs two packages and returns structured change records.
 *
 * Word body parts only for now; other formats fall through as part-level add/remove,
 * which is reported rather than silently skipped.
 */
export const diffPackages = (before: PackageParts, after: PackageParts): DiffResult => {
  const records: ChangeRecord[] = [];
  const normalized: NormalizationReport[] = [];
  const unresolved: string[] = [];
  const parts: string[] = [];

  const allPaths = new Set([...Object.keys(before), ...Object.keys(after)]);

  for (const path of [...allPaths].sort()) {
    if (!(path in after)) {
      records.push({
        kind: 'part-removed', part: path, location: path, before: path, after: null, visible: true,
        remediation: `Add the part ${path} back, along with its content-type declaration and any relationship that referenced it.`
      });
      continue;
    }
    if (!(path in before)) {
      records.push({
        kind: 'part-added', part: path, location: path, before: null, after: path, visible: true,
        remediation: `Remove the part ${path}, together with its content-type declaration and any relationship pointing at it.`
      });
      continue;
    }
    if (!bodyPartPattern.test(path)) continue;

    parts.push(path);

    const parse = (xml: string) => {
      const doc = new DOMParser().parseFromString(xml, 'application/xml');
      return doc.getElementsByTagName('parsererror').length > 0 ? null : doc;
    };
    const beforeDoc = parse(before[path]);
    const afterDoc = parse(after[path]);
    if (!beforeDoc || !afterDoc) {
      unresolved.push(`${path} could not be parsed on one or both sides; it was not compared`);
      continue;
    }

    normalized.push(...normalizePart(beforeDoc), ...normalizePart(afterDoc));

    const { inserted, deleted } = diffAtoms(atomize(beforeDoc), atomize(afterDoc));
    for (const group of groupAtoms(deleted)) {
      records.push({
        kind: 'content-deleted', part: path, location: `paragraph[${group.paragraph}]`,
        before: group.text, after: null, visible: true,
        remediation: `Re-insert the text "${group.text}" in paragraph ${group.paragraph} of ${path}.`
      });
    }
    for (const group of groupAtoms(inserted)) {
      records.push({
        kind: 'content-inserted', part: path, location: `paragraph[${group.paragraph}]`,
        before: null, after: group.text, visible: true,
        remediation: `Remove the text "${group.text}" from paragraph ${group.paragraph} of ${path}.`
      });
    }

    records.push(...diffFormatting(before, after, path, unresolved));
  }

  // Merge the normalization counts so the report is per-rule, not per-part.
  const merged = new Map<string, number>();
  for (const entry of normalized) merged.set(entry.rule, (merged.get(entry.rule) ?? 0) + entry.count);

  return {
    equivalent: records.length === 0,
    records,
    parts,
    normalized: [...merged.entries()].map(([rule, count]) => ({ rule, count })),
    unresolved: [...new Set(unresolved)]
  };
};

/**
 * Renders a diff as prose, for a human reading the panel.
 *
 * Derived from the records rather than produced alongside them, so the structured
 * payload stays the source of truth and the two cannot drift apart.
 */
export const explainDiff = (result: DiffResult): string[] => {
  if (result.equivalent) {
    // The answer worth leading with. A textual diff can show thousands of changed
    // bytes between two files Word treats identically, and someone staring at that
    // diff needs to be told so plainly rather than left to infer it from an empty list.
    const lines = ['These two files are SEMANTICALLY EQUIVALENT - Word will treat them identically.'];
    if (result.normalized.length > 0) {
      lines.push(
        'They do differ textually, but only in ways that carry no meaning:',
        ...result.normalized.map(n => `  ${n.count} × ${n.rule}`),
        'A line-by-line diff will show these as changes. They are not.'
      );
    } else {
      lines.push('No textual noise was filtered either - the parts compared are the same.');
    }
    if (result.unresolved.length > 0) {
      lines.push('Not established (do not assert these):', ...result.unresolved.map(u => `  ${u}`));
    }
    return lines;
  }

  const lines = [`${result.records.length} semantic change(s) across ${result.parts.length} part(s):`];
  for (const record of result.records) {
    const where = `${record.part} ${record.location}`;
    switch (record.kind) {
      case 'content-inserted': lines.push(`  + inserted "${record.after}" at ${where}`); break;
      case 'content-deleted': lines.push(`  − deleted "${record.before}" at ${where}`); break;
      case 'formatting-changed': lines.push(`  ~ ${record.property}: ${record.before} → ${record.after} at ${where}`); break;
      case 'part-added': lines.push(`  + part added: ${record.part}`); break;
      case 'part-removed': lines.push(`  − part removed: ${record.part}`); break;
    }
  }
  if (result.normalized.length > 0) {
    lines.push(`Ignored as rendering-irrelevant: ${result.normalized.map(n => `${n.count} × ${n.rule}`).join(', ')}.`);
  }
  lines.push('', 'To make the second file match the first:');
  for (const record of result.records) lines.push(`  · ${record.remediation}`);
  if (result.unresolved.length > 0) {
    lines.push('Not established (do not assert these):', ...result.unresolved.map(u => `  ${u}`));
  }
  return lines;
};
