// This file is auto-generated by compileKB step in ooxml-rag-ingestion workflow.
// Do not edit this file manually.

export interface ReferenceDoc {
  tag: string;
  namespace: string;
  domain: 'docx' | 'xlsx' | 'pptx' | 'shared';
  definition: string;
  attributes: string[];
  parents: string[];
  citation?: string;
  sdkClass?: string;
  reviewerNote?: string;
  priority?: 'high' | 'low';
}

export const KNOWLEDGE_BASE: ReferenceDoc[] = [
  {
    "tag": "document",
    "namespace": "w",
    "domain": "docx",
    "definition": "The root element of a WordprocessingML main document part. It contains the document's background and body elements, which house the actual document content and structure.",
    "attributes": [
      "conformance"
    ],
    "parents": [],
    "citation": "ECMA-376 Part 1, Section 17.2.3",
    "sdkClass": "Document"
  },
  {
    "tag": "body",
    "namespace": "w",
    "domain": "docx",
    "definition": "Specifies the body of a WordprocessingML document, which contains the main document story. It acts as a container for all block-level elements, such as paragraphs, tables, and section properties, that make up the primary visible content of the document.",
    "attributes": [],
    "parents": [
      "document"
    ],
    "citation": "ECMA-376 Part 1, Section 17.2.2",
    "sdkClass": "Body"
  },
  {
    "tag": "p",
    "namespace": "w",
    "domain": "docx",
    "definition": "Specifies a paragraph of content in a WordprocessingML document. It is the fundamental unit of block-level content, containing paragraph properties (w:pPr) and inline markup such as runs (w:r), hyperlinks, and bookmarks.",
    "attributes": [
      "w:rsidDel",
      "w:rsidP",
      "w:rsidR",
      "w:rsidRDefault",
      "w:rsidRPr",
      "w14:paraId",
      "w14:textId"
    ],
    "parents": [
      "w:body",
      "w:tc",
      "w:sdtContent",
      "w:txbxContent",
      "w:hdr",
      "w:ftr",
      "w:comment",
      "w:footnote",
      "w:endnote"
    ],
    "citation": "ECMA-376 Part 1, Section 17.3.1.22",
    "sdkClass": "Paragraph"
  },
  {
    "tag": "r",
    "namespace": "w",
    "domain": "docx",
    "definition": "Specifies a run of text within a paragraph, representing a region of text with a common set of properties (formatting) and containing text-level elements like text, breaks, and drawings.",
    "attributes": [
      "w:rsidDel",
      "w:rsidR",
      "w:rsidRPr"
    ],
    "parents": [
      "w:p",
      "w:hyperlink",
      "w:sdtContent",
      "w:ins",
      "w:del",
      "w:fldSimple"
    ],
    "citation": "ECMA-376 Part 1, Section 17.3.2.25",
    "sdkClass": "Run"
  },
  {
    "tag": "t",
    "namespace": "w",
    "domain": "docx",
    "definition": "Specifies that the run contains literal text to be displayed in the document. It is the primary element used to represent textual content within a paragraph run.",
    "attributes": [
      "xml:space"
    ],
    "parents": [
      "w:r"
    ],
    "citation": "ECMA-376 Part 1, Section 17.3.3.31",
    "sdkClass": "Text"
  },
  {
    "tag": "tbl",
    "namespace": "w",
    "domain": "docx",
    "definition": "Specifies a table within a WordprocessingML document, containing a set of paragraphs and other block-level content arranged in rows and columns.",
    "attributes": [],
    "parents": [
      "body",
      "comment",
      "customXml",
      "docPartBody",
      "endnote",
      "footnote",
      "ftr",
      "hdr",
      "sdtContent",
      "tc"
    ],
    "citation": "ECMA-376 Part 1, Section 17.4.38",
    "sdkClass": "Table"
  },
  {
    "tag": "tr",
    "namespace": "w",
    "domain": "docx",
    "definition": "Specifies a single row within a table. It acts as a container for table cells (w:tc) and contains optional row-level properties (w:trPr) that define the formatting and behavior of the row.",
    "attributes": [
      "rsidDel",
      "rsidR",
      "rsidRPr",
      "rsidTr"
    ],
    "parents": [
      "tbl",
      "customXml",
      "sdtContent"
    ],
    "citation": "ECMA-376 Part 1, Section 17.4.81",
    "sdkClass": "TableRow"
  },
  {
    "tag": "tc",
    "namespace": "w",
    "domain": "docx",
    "definition": "This element specifies a single cell within a table row, which contains the table's content. It acts as a container for block-level elements, such as paragraphs and nested tables, and can be styled using cell-level properties. To be valid, a table cell must contain at least one block-level element.",
    "attributes": [],
    "parents": [
      "customXml",
      "sdtContent",
      "tr"
    ],
    "citation": "ECMA-376 Part 1, Section 17.4.66",
    "sdkClass": "TableCell"
  },
  {
    "tag": "cantSplit",
    "namespace": "w",
    "domain": "docx",
    "definition": "Specifies that the contents of the current table row must not be split across multiple pages when a page break occurs. If the row cannot fit on the remainder of the page, the entire row is moved to the start of the next page.",
    "attributes": [
      "val"
    ],
    "parents": [
      "trPr"
    ],
    "citation": "ECMA-376 Part 1, Section 17.4.6",
    "sdkClass": "CantSplit"
  },
  {
    "tag": "tblHeader",
    "namespace": "w",
    "domain": "docx",
    "definition": "Specifies that the current table row shall be repeated at the top of each new page on which the table is displayed, acting as a header row. This is used for multi-page tables to ensure the header row remains visible.",
    "attributes": [
      "val"
    ],
    "parents": [
      "trPr"
    ],
    "citation": "ECMA-376 Part 1, Section 17.4.50",
    "sdkClass": "TableHeader"
  },
  {
    "tag": "worksheet",
    "namespace": "r",
    "domain": "xlsx",
    "definition": "The root element of a Worksheet part in a SpreadsheetML document. It contains the sheet's properties, dimensions, views, cell data (sheetData), and other sheet-specific configurations like page setup, protection, and drawings.",
    "attributes": [],
    "parents": [],
    "citation": "ECMA-376 Part 1, Section 18.3.1.99",
    "sdkClass": "Worksheet"
  },
  {
    "tag": "sheetData",
    "namespace": "s",
    "domain": "xlsx",
    "definition": "This element represents the cell table for the worksheet, acting as a container for the individual rows and cells. It holds all the grid data, including cell values, formulas, and formatting references.",
    "attributes": [],
    "parents": [
      "worksheet"
    ],
    "citation": "ECMA-376 Part 1, Section 18.3.1.80",
    "sdkClass": "SheetData"
  },
  {
    "tag": "row",
    "namespace": "r",
    "domain": "xlsx",
    "definition": "This element represents a single row in a worksheet's grid and acts as a container for the individual cells (c) within that row. It defines row-level properties including the 1-based row index (r), custom height (ht), style formatting index (s), outline level, and visibility states such as hidden or collapsed.",
    "attributes": [
      "collapsed",
      "customFormat",
      "customHeight",
      "hidden",
      "ht",
      "outlineLevel",
      "ph",
      "r",
      "s",
      "spans",
      "thickBot",
      "thickTop"
    ],
    "parents": [
      "sheetData"
    ],
    "citation": "ECMA-376 Part 1, Section 18.3.1.73",
    "sdkClass": "DocumentFormat.OpenXml.Spreadsheet.Row"
  },
  {
    "tag": "c",
    "namespace": "r",
    "domain": "xlsx",
    "definition": "Represents a cell in a worksheet. It is the fundamental element for storing data, formulas, and formatting references within a grid row.",
    "attributes": [
      "r",
      "s",
      "t",
      "cm",
      "vm",
      "ph"
    ],
    "parents": [
      "row"
    ],
    "citation": "ECMA-376 Part 1, Section 18.3.1.4",
    "sdkClass": "DocumentFormat.OpenXml.Spreadsheet.Cell"
  },
  {
    "tag": "v",
    "namespace": "r",
    "domain": "xlsx",
    "definition": "Cell Value. Contains the raw value of the cell. The interpretation of this value depends on the 't' (type) attribute of the parent 'c' (cell) element: it can be a number, a boolean ('0' or '1'), an error code, or a zero-based index into the Shared String Table.",
    "attributes": [],
    "parents": [
      "c"
    ],
    "citation": "ECMA-376 Part 1, Section 18.3.1.96",
    "sdkClass": "CellValue"
  },
  {
    "tag": "f",
    "namespace": "r",
    "domain": "xlsx",
    "definition": "Defines the formula expression for a cell, which can be a normal, shared, array, or data table formula. It contains the formula string as its text content and supports various attributes to control calculation behavior, cell ranges, and sharing.",
    "attributes": [
      "aca",
      "bx",
      "ca",
      "del1",
      "del2",
      "dt2D",
      "dtr",
      "r1",
      "r2",
      "ref",
      "si",
      "t"
    ],
    "parents": [
      "c",
      "nc",
      "oc"
    ],
    "citation": "ECMA-376 Part 1, Section 18.3.1.40",
    "sdkClass": "CellFormula"
  },
  {
    "tag": "sst",
    "namespace": "s",
    "domain": "xlsx",
    "definition": "The sst element defines the Shared String Table, which stores a single unique copy of each text string used across all worksheets in the spreadsheet. Rather than repeating literal strings in individual cells, cells reference these strings by their zero-based index to optimize file size. It also records the total and unique count of strings in the workbook.",
    "attributes": [
      "count",
      "uniqueCount"
    ],
    "parents": [],
    "citation": "ECMA-376 Part 1, Section 18.4.9",
    "sdkClass": "SharedStringTable"
  },
  {
    "tag": "si",
    "namespace": "s",
    "domain": "xlsx",
    "definition": "This element represents an individual string in the Shared String Table. It can contain either a simple text value or a complex set of rich text runs with character-level formatting.",
    "attributes": [],
    "parents": [
      "sst"
    ],
    "citation": "ECMA-376 Part 1, Section 18.4.8",
    "sdkClass": "SharedStringItem"
  },
  {
    "tag": "presentation",
    "namespace": "p",
    "domain": "pptx",
    "definition": "This element specifies the root of a PresentationML document, defining fundamental presentation-wide properties. It serves as the container for slide master lists, slide ID lists, slide size configurations, and default text styles. It also manages global presentation settings such as auto-compression of pictures and right-to-left language support.",
    "attributes": [
      "autoCompressPictures",
      "bookmarkIdSeed",
      "compatMode",
      "conformance",
      "embedTrueTypeFonts",
      "firstSlideNum",
      "removePersonalInfoOnSave",
      "rtl",
      "saveSubsetFonts",
      "serverZoom",
      "showSpecialPlsOnTitleSld",
      "strictFirstAndLastChars"
    ],
    "parents": [],
    "citation": "ECMA-376 Part 1, Section 19.2.1.26",
    "sdkClass": "Presentation"
  },
  {
    "tag": "sld",
    "namespace": "p",
    "domain": "pptx",
    "definition": "Specifies a slide within a PresentationML document. It is the root element of a PresentationML Slide part and contains slide-specific data, including shapes, transitions, and timing information.",
    "attributes": [
      "show",
      "showMasterPhAnim",
      "showMasterSp"
    ],
    "parents": [],
    "citation": "ECMA-376 Part 1, Section 19.3.1.38",
    "sdkClass": "Slide"
  },
  {
    "tag": "sldLayout",
    "namespace": "p",
    "domain": "pptx",
    "definition": "This element specifies a slide layout, which defines the default positioning, sizing, and formatting of placeholders and shapes for slides that inherit from it. It acts as a template for individual slides while inheriting common design elements from the slide master.",
    "attributes": [
      "matchingName",
      "preserve",
      "showMasterPhAnim",
      "showMasterSp",
      "type",
      "userDrawn"
    ],
    "parents": [],
    "citation": "ECMA-376 Part 1, Section 19.3.1.33",
    "sdkClass": "SlideLayout"
  },
  {
    "tag": "sldMaster",
    "namespace": "p",
    "domain": "pptx",
    "definition": "This element specifies the slide master, which serves as the master template for slides in a presentation. It defines the default formatting, color schemes, slide layouts, and placeholders that are inherited by slide layouts and individual slides.",
    "attributes": [
      "preserve"
    ],
    "parents": [],
    "citation": "ECMA-376 Part 1, Section 19.3.1.42",
    "sdkClass": "SlideMaster"
  },
  {
    "tag": "sp",
    "namespace": "p",
    "domain": "pptx",
    "definition": "This element specifies the existence of a single shape within a slide or group shape. A shape can either be a preset or a custom geometry, defined using the DrawingML framework, and can have visual, non-visual, styling, and text properties attached.",
    "attributes": [
      "useBgFill"
    ],
    "parents": [
      "grpSp",
      "spTree"
    ],
    "citation": "ECMA-376 Part 1, Section 19.3.1.40",
    "sdkClass": "Shape"
  },
  {
    "tag": "txBody",
    "namespace": "p",
    "domain": "pptx",
    "definition": "This element specifies the existence of text to be contained within the corresponding shape. All visible text and visible text related properties are contained within this element.",
    "attributes": [],
    "parents": [
      "sp"
    ],
    "citation": "ECMA-376 Part 1, Section 19.3.1.43",
    "sdkClass": "TextBody"
  },
  {
    "tag": "Relationships",
    "namespace": "rel",
    "domain": "shared",
    "definition": "The root element of a relationship part (.rels) in an Open Packaging Conventions (OPC) package. It serves as a container for one or more Relationship elements, which define the associations between a source part and target resources.",
    "attributes": [],
    "parents": [],
    "citation": "ECMA-376 Part 2, Section 9.3.2",
    "sdkClass": "System.IO.Packaging.PackageRelationshipCollection"
  },
  {
    "tag": "Relationship",
    "namespace": "rel",
    "domain": "shared",
    "definition": "Defines a relationship between a source package or part and a target resource. It specifies the unique identifier, relationship type, target URI, and whether the target is internal or external to the package.",
    "attributes": [
      "Id",
      "Type",
      "Target",
      "TargetMode"
    ],
    "parents": [
      "Relationships"
    ],
    "citation": "ECMA-376 Part 2, Section 9.3.1",
    "sdkClass": "PackageRelationship"
  },
  {
    "tag": "Types",
    "namespace": "contentTypes",
    "domain": "shared",
    "definition": "The root element of the content types stream ([Content_Types].xml) in an OOXML package. It defines the content types of all parts in the package using Default and Override child elements to map file extensions and part paths to their respective MIME types.",
    "attributes": [],
    "parents": [],
    "citation": "ECMA-376 Part 2, Section 9.1.2",
    "sdkClass": "None"
  },
  {
    "tag": "Override",
    "namespace": "contentTypes",
    "domain": "shared",
    "definition": "Specifies a content type override for a specific part in the package. This element explicitly associates a content type with a single part name, taking precedence over any default content type mappings.",
    "attributes": [
      "PartName",
      "ContentType"
    ],
    "parents": [
      "Types"
    ],
    "citation": "ECMA-376 Part 2, Section 9.1.3",
    "sdkClass": "OverrideContentType"
  },
  {
    "tag": "Default",
    "namespace": "contentTypes",
    "domain": "shared",
    "definition": "Defines the default content type to be applied to all package parts with a specific file extension. It maps a file extension to a media type (MIME type) within the package's Content Types stream.",
    "attributes": [
      "Extension",
      "ContentType"
    ],
    "parents": [
      "Types"
    ],
    "citation": "ECMA-376 Part 2, Section 9.1.2.2",
    "sdkClass": "DefaultType"
  }
];
