// This file is auto-generated by scripts/ingestSchema.ts.
// To regenerate: pnpm run ingest:schema
// Do not edit this file manually.

export interface ReferenceDoc {
  tag: string;
  namespace: string;
  domain: 'docx' | 'xlsx' | 'pptx' | 'shared';
  /**
   * Human-readable prose. Optional because the bulk of the dataset is generated from
   * the Open XML SDK's schema metadata, which supplies structure but no usable
   * description - its own `Summary` field is boilerplate ("Defines the Table Class.")
   * and sometimes wrong, so generating from it would manufacture false authority.
   * Records without a definition are structurally grounded only; see ragRouter.
   */
  definition?: string;
  attributes: string[];
  parents: string[];
  citation?: string;
  sdkClass?: string;
  reviewerNote?: string;
  priority?: 'high' | 'low';
  /** `curated` records were written by a human; `schema` records are generated. */
  provenance?: 'curated' | 'schema';
}

/**
 * Offline fallback consulted by ragRouter when IndexedDB has no answer - because the
 * store has not been populated yet, the /rag-data.json fetch failed, or IndexedDB is
 * unavailable entirely. Only the curated subset is bundled; the full corpus lives in
 * public/rag-data.json.
 */
export const KNOWLEDGE_BASE: ReferenceDoc[] = [
  {
    "tag": "body",
    "namespace": "w",
    "domain": "docx",
    "attributes": [],
    "parents": [
      "w:document"
    ],
    "sdkClass": "Body",
    "provenance": "curated",
    "definition": "This element specifies the body of a WordprocessingML document, which contains the main document story. It houses the primary block-level content, such as paragraphs, tables, and the section properties for the final section of the document.",
    "citation": "ECMA-376 Part 1, Section 17.2.1"
  },
  {
    "tag": "cantSplit",
    "namespace": "w",
    "domain": "docx",
    "attributes": [
      "w:val"
    ],
    "parents": [
      "w:trPr"
    ],
    "sdkClass": "CantSplit",
    "provenance": "curated",
    "definition": "Specifies that the contents of the current table row must not be split across multiple pages when a page break occurs. If the row cannot fit on the remainder of the page, the entire row is moved to the start of the next page.",
    "citation": "ECMA-376 Part 1, Section 17.4.6"
  },
  {
    "tag": "document",
    "namespace": "w",
    "domain": "docx",
    "attributes": [
      "w:conformance"
    ],
    "parents": [
      "a:graphicData"
    ],
    "sdkClass": "Document",
    "provenance": "curated",
    "definition": "Specifies the root element for the main document part of a WordprocessingML document. It contains the body element, which holds the primary document content such as paragraphs, tables, and sections.",
    "citation": "ECMA-376 Part 1, Section 17.2.3"
  },
  {
    "tag": "p",
    "namespace": "w",
    "domain": "docx",
    "attributes": [
      "w14:noSpellErr",
      "w14:paraId",
      "w14:textId",
      "w:rsidDel",
      "w:rsidP",
      "w:rsidR",
      "w:rsidRDefault",
      "w:rsidRPr"
    ],
    "parents": [
      "w:body",
      "w:comment",
      "w:customXml",
      "w:docPartBody",
      "w:endnote",
      "w:footnote",
      "w:ftr",
      "w:hdr",
      "w:sdtContent",
      "w:tc",
      "w:txbxContent"
    ],
    "sdkClass": "Paragraph",
    "provenance": "curated",
    "definition": "Specifies a paragraph of content within a WordprocessingML document. It is the basic unit of block-level content, containing optional paragraph properties and one or more inline runs of text, drawings, or fields.",
    "citation": "ECMA-376 Part 1, Section 17.3.1.22"
  },
  {
    "tag": "r",
    "namespace": "w",
    "domain": "docx",
    "attributes": [
      "w:rsidDel",
      "w:rsidR",
      "w:rsidRPr"
    ],
    "parents": [
      "w:bdo",
      "w:customXml",
      "w:del",
      "w:dir",
      "w:fldSimple",
      "w:hyperlink",
      "w:ins",
      "w:moveFrom",
      "w:moveTo",
      "w:p",
      "w:rt",
      "w:rubyBase",
      "w:sdtContent"
    ],
    "sdkClass": "Run",
    "provenance": "curated",
    "definition": "Specifies a run of content in a WordprocessingML document. It acts as a container for inline elements and text that share a common set of properties, such as formatting and styles.",
    "citation": "ECMA-376 Part 1, Section 17.3.2.25"
  },
  {
    "tag": "t",
    "namespace": "w",
    "domain": "docx",
    "attributes": [
      "xml:space"
    ],
    "parents": [
      "w:r"
    ],
    "sdkClass": "Text",
    "provenance": "curated",
    "definition": "Specifies the literal text content of a run in a WordprocessingML document. This element contains the actual string data to be displayed and can preserve whitespace through the xml:space attribute.",
    "citation": "ECMA-376 Part 1, Section 17.3.3.31"
  },
  {
    "tag": "tbl",
    "namespace": "w",
    "domain": "docx",
    "attributes": [],
    "parents": [
      "w:body",
      "w:comment",
      "w:customXml",
      "w:docPartBody",
      "w:endnote",
      "w:footnote",
      "w:ftr",
      "w:hdr",
      "w:sdtContent",
      "w:tc",
      "w:txbxContent"
    ],
    "sdkClass": "Table",
    "provenance": "curated",
    "definition": "Specifies a table in a WordprocessingML document. A table is a block-level element that contains a set of table rows and cells, which are used to arrange text, images, and other content in a grid structure.",
    "citation": "ECMA-376 Part 1, Section 17.4.38"
  },
  {
    "tag": "tblHeader",
    "namespace": "w",
    "domain": "docx",
    "attributes": [
      "w:val"
    ],
    "parents": [
      "w:trPr"
    ],
    "sdkClass": "TableHeader",
    "provenance": "curated",
    "definition": "Specifies that the current table row shall be repeated at the top of each new page on which the table is displayed, acting as a header row. This is used for multi-page tables to ensure the header row remains visible.",
    "citation": "ECMA-376 Part 1, Section 17.4.50"
  },
  {
    "tag": "tc",
    "namespace": "w",
    "domain": "docx",
    "attributes": [],
    "parents": [
      "w:customXml",
      "w:sdtContent",
      "w:tr"
    ],
    "sdkClass": "TableCell",
    "provenance": "curated",
    "definition": "Defines a single cell within a table row of a table. It acts as a container for block-level elements, such as paragraphs and nested tables, which hold the actual cell content. It also contains cell-specific properties that define formatting and layout rules for the cell.",
    "citation": "ECMA-376 Part 1, Section 17.4.66"
  },
  {
    "tag": "tr",
    "namespace": "w",
    "domain": "docx",
    "attributes": [
      "w14:paraId",
      "w14:textId",
      "w:rsidDel",
      "w:rsidR",
      "w:rsidRPr",
      "w:rsidTr"
    ],
    "parents": [
      "w:customXml",
      "w:sdtContent",
      "w:tbl"
    ],
    "sdkClass": "TableRow",
    "provenance": "curated",
    "definition": "Specifies a single row within a table in a WordprocessingML document. This element acts as a container for table cells (tc) and row-level formatting properties (trPr).",
    "citation": "ECMA-376 Part 1, Section 17.4.81"
  },
  {
    "tag": "presentation",
    "namespace": "p",
    "domain": "pptx",
    "attributes": [
      ":autoCompressPictures",
      ":bookmarkIdSeed",
      ":compatMode",
      ":conformance",
      ":embedTrueTypeFonts",
      ":firstSlideNum",
      ":removePersonalInfoOnSave",
      ":rtl",
      ":saveSubsetFonts",
      ":serverZoom",
      ":showSpecialPlsOnTitleSld",
      ":strictFirstAndLastChars"
    ],
    "parents": [
      "a:graphicData"
    ],
    "sdkClass": "Presentation",
    "provenance": "curated",
    "definition": "Specifies the root element for a PresentationML document, containing presentation-wide properties such as slide size, notes size, default text styles, and references to slide masters and slides.",
    "citation": "ECMA-376 Part 1, Section 19.2.1.25"
  },
  {
    "tag": "sld",
    "namespace": "p",
    "domain": "pptx",
    "attributes": [
      ":collapse",
      ":show",
      ":showMasterPhAnim",
      ":showMasterSp",
      "r:id"
    ],
    "parents": [
      "a:graphicData",
      "p:sldLst"
    ],
    "sdkClass": "OutlineViewSlideListEntry",
    "provenance": "curated",
    "definition": "Slide. The root element representing a single slide within the presentation.",
    "citation": "ECMA-376 Part 1, Section 19.3.1.38"
  },
  {
    "tag": "sldLayout",
    "namespace": "p",
    "domain": "pptx",
    "attributes": [
      ":matchingName",
      ":preserve",
      ":showMasterPhAnim",
      ":showMasterSp",
      ":type",
      ":userDrawn"
    ],
    "parents": [
      "a:graphicData"
    ],
    "sdkClass": "SlideLayout",
    "provenance": "curated",
    "definition": "This element specifies an instance of a slide layout. It contains a template slide design that can be applied to any slide in a presentation, defining the default positioning and formatting of placeholders and other shapes.",
    "citation": "ECMA-376 Part 1, Section 19.2.1.38"
  },
  {
    "tag": "sldMaster",
    "namespace": "p",
    "domain": "pptx",
    "attributes": [
      ":preserve"
    ],
    "parents": [
      "a:graphicData"
    ],
    "sdkClass": "SlideMaster",
    "provenance": "curated",
    "definition": "Specifies an instance of a slide master slide. It contains all elements that describe the objects and their corresponding formatting for slides within a presentation, including shapes, text styles, color maps, and transitions.",
    "citation": "ECMA-376 Part 1, Section 19.3.1.42"
  },
  {
    "tag": "sp",
    "namespace": "p",
    "domain": "pptx",
    "attributes": [
      ":useBgFill"
    ],
    "parents": [
      "p:grpSp",
      "p:spTree"
    ],
    "sdkClass": "Shape",
    "provenance": "curated",
    "definition": "This element specifies the existence of a single shape. A shape can either be a preset or a custom geometry defined using the DrawingML framework, and can have visual properties, non-visual properties, text, and styling attached.",
    "citation": "ECMA-376 Part 1, Section 19.3.1.43"
  },
  {
    "tag": "txBody",
    "namespace": "p",
    "domain": "pptx",
    "attributes": [],
    "parents": [
      "p:sp"
    ],
    "sdkClass": "TextBody",
    "provenance": "curated",
    "definition": "This element specifies the text body to be contained within a shape in a presentation. It houses all the visible text, paragraph formatting, and text body properties such as columns and wrapping. The text within this element is structured into one or more paragraphs containing text runs.",
    "citation": "ECMA-376 Part 1, Section 19.3.1.51"
  },
  {
    "tag": "Default",
    "namespace": "r",
    "domain": "shared",
    "definition": "Specifies a default content type that will be associated with all parts in the package that have the extension specified in the Extension attribute.",
    "attributes": [
      "Extension",
      "ContentType"
    ],
    "parents": [
      "Types"
    ],
    "citation": "ECMA-376 Part 2, Section 9.1.2.2",
    "sdkClass": "DefaultType",
    "provenance": "curated"
  },
  {
    "tag": "Override",
    "namespace": "r",
    "domain": "shared",
    "definition": "Content Type Override. Specifies the content type of a specific part inside the ZIP package, overriding defaults.",
    "attributes": [
      "PartName",
      "ContentType"
    ],
    "parents": [
      "Types"
    ],
    "citation": "ECMA-376 Part 2, Section 9.1.2.3",
    "sdkClass": "Override",
    "provenance": "curated"
  },
  {
    "tag": "Relationship",
    "namespace": "r",
    "domain": "shared",
    "definition": "Defines a single relationship between a source package or part and a target resource. It specifies a unique identifier, the relationship type (defining its role), and the target URI.",
    "attributes": [
      "Id",
      "Type",
      "Target",
      "TargetMode"
    ],
    "parents": [
      "Relationships"
    ],
    "citation": "ECMA-376 Part 2, Section 9.3",
    "sdkClass": "System.IO.Packaging.PackageRelationship",
    "provenance": "curated"
  },
  {
    "tag": "Relationships",
    "namespace": "r",
    "domain": "shared",
    "definition": "The Relationships element is the root element of a relationship part (.rels) in an Open Packaging Conventions (OPC) package. It acts as a container for one or more Relationship elements that define associations between a source part and target resources.",
    "attributes": [],
    "parents": [],
    "citation": "ECMA-376 Part 2, Section 9.3.1",
    "sdkClass": "PackageRelationshipCollection",
    "provenance": "curated"
  },
  {
    "tag": "Types",
    "namespace": "r",
    "domain": "shared",
    "definition": "The Types element is the root element of the Content Types stream ([Content_Types].xml) in an OPC package. It contains the default and override content type mappings that define the media types for all parts in the package.",
    "attributes": [],
    "parents": [],
    "citation": "ECMA-376 Part 2, Section 9.1.2",
    "sdkClass": "Types",
    "provenance": "curated"
  },
  {
    "tag": "c",
    "namespace": "x",
    "domain": "xlsx",
    "attributes": [
      ":a",
      ":cm",
      ":i",
      ":l",
      ":ph",
      ":r",
      ":s",
      ":t",
      ":vm"
    ],
    "parents": [
      "x:calcChain",
      "x:row"
    ],
    "sdkClass": "Cell",
    "provenance": "curated",
    "definition": "Represents a cell in a worksheet. It is the core container for cell data, including its value, formula, style formatting index, and data type.",
    "citation": "ECMA-376 Part 1, Section 18.3.1.4"
  },
  {
    "tag": "f",
    "namespace": "x",
    "domain": "xlsx",
    "attributes": [
      ":aca",
      ":bx",
      ":ca",
      ":del1",
      ":del2",
      ":dt2D",
      ":dtr",
      ":r1",
      ":r2",
      ":ref",
      ":si",
      ":t",
      "xml:space"
    ],
    "parents": [
      "x:c",
      "x:nc",
      "x:oc"
    ],
    "sdkClass": "CellFormula",
    "provenance": "curated",
    "definition": "Defines the formula expression for a cell, which can be a normal, shared, array, or data table formula. It contains the formula string as its text content and supports various attributes to control calculation behavior, cell ranges, and sharing.",
    "citation": "ECMA-376 Part 1, Section 18.3.1.40"
  },
  {
    "tag": "row",
    "namespace": "x",
    "domain": "xlsx",
    "attributes": [
      ":collapsed",
      ":customFormat",
      ":customHeight",
      ":hidden",
      ":ht",
      ":outlineLevel",
      ":ph",
      ":r",
      ":s",
      ":spans",
      ":thickBot",
      ":thickTop",
      "x14ac:dyDescent"
    ],
    "parents": [
      "x:sheetData"
    ],
    "sdkClass": "ExternalRow",
    "provenance": "curated",
    "definition": "This element represents a single row in a worksheet's grid and acts as a container for the individual cells (c) within that row. It defines row-level properties including the 1-based row index (r), custom height (ht), style formatting index (s), outline level, and visibility states such as hidden or collapsed.",
    "citation": "ECMA-376 Part 1, Section 18.3.1.73"
  },
  {
    "tag": "sheetData",
    "namespace": "x",
    "domain": "xlsx",
    "attributes": [
      ":refreshError",
      ":sheetId"
    ],
    "parents": [
      "x:sheetDataSet",
      "x:worksheet"
    ],
    "sdkClass": "SheetData",
    "provenance": "curated",
    "definition": "The sheetData element represents the table grid of a worksheet in a SpreadsheetML document. It acts as the container for all row and cell elements, organizing the actual cell data and formulas of the sheet.",
    "citation": "ECMA-376 Part 1, Section 18.3.1.80"
  },
  {
    "tag": "si",
    "namespace": "x",
    "domain": "xlsx",
    "attributes": [],
    "parents": [
      "x:sst"
    ],
    "sdkClass": "SharedStringItem",
    "provenance": "curated",
    "definition": "This element represents an individual string in the Shared String Table. It can contain either a simple text value or a complex set of rich text runs with character-level formatting.",
    "citation": "ECMA-376 Part 1, Section 18.4.8"
  },
  {
    "tag": "sst",
    "namespace": "x",
    "domain": "xlsx",
    "attributes": [
      ":count",
      ":uniqueCount"
    ],
    "parents": [],
    "sdkClass": "SharedStringTable",
    "provenance": "curated",
    "definition": "The sst element defines the Shared String Table, which stores a single unique copy of each text string used across all worksheets in the spreadsheet. Rather than repeating literal strings in individual cells, cells reference these strings by their zero-based index to optimize file size. It also records the total and unique count of strings in the workbook.",
    "citation": "ECMA-376 Part 1, Section 18.4.9"
  },
  {
    "tag": "v",
    "namespace": "x",
    "domain": "xlsx",
    "attributes": [
      "xml:space"
    ],
    "parents": [
      "x:c",
      "x:cell",
      "x:nc",
      "x:oc",
      "x:tp"
    ],
    "sdkClass": "Xstring",
    "provenance": "curated",
    "definition": "The Cell Value element expresses the direct value of a worksheet cell. It contains the raw data, such as a numeric value, a boolean representation, an error code, or a zero-based index pointing to a shared string in the shared string table.",
    "citation": "ECMA-376 Part 1, Section 18.3.1.96"
  },
  {
    "tag": "worksheet",
    "namespace": "x",
    "domain": "xlsx",
    "attributes": [],
    "parents": [],
    "sdkClass": "Worksheet",
    "provenance": "curated",
    "definition": "Represents the root element of a worksheet in a SpreadsheetML document. It contains all the sheets' data, columns, rows, cell formatting, and other properties that define the structure and content of an individual sheet.",
    "citation": "ECMA-376 Part 1, Section 18.3.1.99"
  }
];
